---
# Source: artifactory/templates/artifactory-access-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-artifactory-access-config
  labels:
    app: artifactory
    chart: artifactory-107.47.11
    heritage: Helm
    release: test
type: Opaque
stringData:
  access.config.patch.yml: |
    security:
      tls: false
