---
# Source: artifactory/templates/artifactory-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-artifactory
  labels:
    app: artifactory
    chart: artifactory-107.47.11
    component: artifactory
    heritage: Helm
    release: test
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http-router
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http-artifactory
  selector:
    app: artifactory
    component: "artifactory"
    release: test
