---
# Source: artifactory/templates/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-artifactory-nginx
  labels:
    app: artifactory
    chart: artifactory-107.47.11
    heritage: Helm
    release: test
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
      release: test
      component: nginx
  template:
    metadata:
      annotations:
        checksum/nginx-conf: 800ca344439dc9a60db5bf1fae363526f87c046ee60e307709ddbe04baa8d339
        checksum/nginx-artifactory-conf: 848bc7d8f44b26a0ee32b158b18338f2d4c6a23eba57586581d4cef244e6030e
      labels:
        app: artifactory
        chart: artifactory-107.47.11
        component: nginx
        heritage: Helm
        release: test
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: "setup"
        image: "releases-docker.jfrog.io/ubi8/ubi-minimal:8.6-941"
        imagePullPolicy: IfNotPresent
        command:
        - '/bin/sh'
        - '-c'
        - >
          rm -rfv /var/opt/jfrog/nginx/lost+found;
          mkdir -p /var/opt/jfrog/nginx/logs;
        volumeMounts:
        - mountPath: "/var/opt/jfrog/nginx"
          name: nginx-volume
      containers:
      - name: nginx
        image: releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:latest
        imagePullPolicy: IfNotPresent
        command:          
          - nginx
          - -g
          - 'daemon off;'
        ports:

        # DEPRECATION NOTE: The following is to maintain support for values pre 1.3.1 and
        # will be cleaned up in a later version
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-artifactory-conf
          mountPath: "/var/opt/jfrog/nginx/conf.d/"
        - name: nginx-volume
          mountPath: "/var/opt/jfrog/nginx"
        - name: ssl-certificates
          mountPath: "/var/opt/jfrog/nginx/ssl"
        resources:
          {}
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - curl -s -k --fail --max-time 5 http://localhost:8080/router/api/v1/system/readiness
          initialDelaySeconds: 30
          failureThreshold: 90
          periodSeconds: 5
          timeoutSeconds: 5
          
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - curl -s -k --fail --max-time 5 http://localhost:8080/router/api/v1/system/readiness
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
          
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - curl -s -k --fail --max-time 5 http://localhost:8080/
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
          
      volumes:
      - name: nginx-conf
        configMap:
          name: test-artifactory-nginx-conf
      - name: nginx-artifactory-conf
        configMap:
          name: test-artifactory-nginx-artifactory-conf
      - name: nginx-volume
        emptyDir: {}
      - name: ssl-certificates
        secret:
          secretName: test-artifactory-nginx-certificate
