---
# Source: artifactory/templates/nginx-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-artifactory-nginx
  labels:
    app: artifactory
    chart: artifactory-107.47.11
    component: nginx
    heritage: Helm
    release: test
spec:
  selector:
    matchLabels:
      component: nginx
      app: artifactory
      release: test
  minAvailable: 0
